# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-25 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
